//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teste_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int idfuncionarios { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string rg { get; set; }
        public string endereco { get; set; }
        public string salario { get; set; }
    }
}
